# Generated by Django 4.2.6 on 2024-06-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='email',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
